### ISSUE TITLE
Mutation Events для событий изменения DOM

### ISSUE THREAD

**Issue by noway421** [nickkolok/chas-correct#1]
Больно костыльно по таймеру все перепроверять.

**Comment by nickkolok** [comment]
Таймер там только для того, чтобы несколько подряд идущих DOMChanged обрабатывать вместе, после последнего.

**Comment by nickkolok** [comment]
Посмотрите, Вы это имели в виду?
https://github.com/nickkolok/chas-correct/blob/e4426d25e1ab100cdf2dc3aa73e9647f5f294d9e/chrome/content.js#L481

**Comment by noway421** [comment]
Да, это. Хорошо пофиксили.

**Comment by nickkolok** [comment]
Спасибо! Закрываю.
