### ISSUE TITLE
"script unresponsive" на ленте вконтакта (FF, OsX)

### ISSUE THREAD

**Issue by Katzen-Gott** [nickkolok/chas-correct#19]
У меня как правило висит открытая вкладка с лентой vk.com. При этом если я переключась в Хром (там расширение не стоит, хотя, не думаю, что это важно), то через десяток минут примерно, в фоксе вылезает алерт "script unresponsive". Да и в целом фокс стал тормозить после того как я установила собранное локально расширение (старую версию я удалила). Перепорверила с текущей версией кода: очень тормозит.
Текст ошибки:
```
Script: resource://gre/modules/commonj…k/chas-correct/data/content.js:407
```

**Comment by nickkolok** [comment]
Собирали из текущей версии с гитхаба?

**Comment by nickkolok** [comment]
Строка 407 - это поиск в кэше. Странно, изучаю.

**Comment by nickkolok** [comment]
Попробуйте запустить firefox из консоли (просто запустить), зайти ВК и посмотреть логи - расширение не напишет, сколько в кэше нод?

**Comment by Katzen-Gott** [comment]
Собирала из текущей версии с гитхаба, да. Пробовала сама посмотреть что там, но не разобралась.

**Comment by Katzen-Gott** [comment]
Если это про поиск в кеше, то может это быть связано с тем, что страница вроде бы меняется (приходят новые записи), но при этом очень много записей есть в кеше (почти все, собственно)?

**Comment by nickkolok** [comment]
Баг с переполнением кэша уже был... И он был пофиксен. 
Всегда именно на этой строке?

Попробуйте в prepareDictionary.js подрихтовать функцию correct.logToConsole так, чтобы она, например, добавляла в head какой-нибудь элемент с текстом сообщения или ещё как-то передавала сообщение. (Отладочный алерт Вас просто замучает.) Пример - 
  var d=document.createElement('link');
  d.innerHTML='';
  document.head.appendChild(d);

**Comment by nickkolok** [comment]
И ещё уточнение: в старой версии такого не наблюдалось?

**Comment by nickkolok** [comment]
Кстати, обрадую: есть ряд усовершенствований движка, которые должны увеличить быстродействие. Как приведу в приличный вид - выложу.

**Comment by nickkolok** [comment]
Баг отловлен. Привожу полную историю:

Я неверно истолковал документацию. Там было написано, что если обсерверу дом два раза указать функцию-колбэк, то вторая заменит первую, и далее по индукции.
Сам код с созданием обсервера было откуда-то скопипащен, потом исправлен во многих местах... В результате после каждого цикла исправлений создавался новый обсервер. С тем же заданием. Но хэндлер не исполнялся подряд чаще, чем раз в полторы секкнды, и потому прогрессия была арифметической, а не геометрической.
Вообще это хорошо, но заметить баг сильно мешало. И я начал его воспроизводить. Открыл лису. Оставил открытыми диалоги, а в хроме переписывался. Потом по номерам строк в сообщении о подвисании скрипта определил, что оно виснет при выборе ссылок на ноды, а вовсе не в блоке исправления ошибок.
Причём в тривиальном цикле выбора из массива элементов, удовлетворяющих численному условию. И тут я понял, что этот выбор вызывается обсервером. А вернее, обсерверами, потому и виснет.

Всё, перенес создание обсервера в функцию, исполняемую один раз, и никаких проблем.
