### ISSUE TITLE
В firefox показывается как firefox 0.1

### ISSUE THREAD

**Issue by positronium** [nickkolok/chas-correct#2]
В менеджере дополнений Firefox отображается как "firefox 0.1 basic add-on".
Следует pull request сделать, но нужно разбираться со разработкой и сборкой расширений. К сожалению, времени пока нет.

**Comment by nickkolok** [comment]
Вот здесь идёт работа: https://github.com/lexqt/chas-correct/commit/c12b4ab824373a329c0064db00a414ca563dd1fa
Если удастся сделать так, что состояние кнопки будет "запоминаться", как, например, у адблока, то смёржим в основную ветку.

**Comment by nickkolok** [comment]
Да и просто переименование будет с радостью принято :-)

**Comment by nickkolok** [comment]
https://github.com/lexqt/chas-correct/commit/c27a394e7a0450decb28c1f4d447b617e1342ccd
