### ISSUE TITLE
проблема со span тегами

### ISSUE THREAD

**Issue by Katzen-Gott** [nickkolok/chas-correct#20]
http://aldebaran.ru/author/fillips_feyinman_richard/kniga_kakoe_tebe_delo_do_togo_chto_dumayut_drugie/ если открыть вкладку "читать онлайн" и перейти на 27ю страницу, можно увидеть слово "чтокировало".
Я не знаю зачем, но там весь текст поделен на кусочки по 2-4 символа, и каждый кусочек завернут в свой `span`. Можно  это как-то обрабатывать, или производительность пострадает?
Я видела такое пока что только в одном месте, но возможно, где-то еще так делают...

**Comment by nickkolok** [comment]
Полагаю, что такие ситуации обрабатывать невозможно. Каждый кусочек текста внутри html-тэга (текстовая нода DOM-дерева) обрабатывается отдельно. Можно только написать плагин для этого конкретного сайта, чтобы "разворачивал".

**Comment by Katzen-Gott** [comment]
Ну нет так нет. Я один раз только альдебараном попользовалась. И есть множество сайтов с более удобными ридерами.
