### ISSUE TITLE
Обновление для Firefox Quantum

### ISSUE THREAD

**Issue by hubslave** [nickkolok/chas-correct#37]
На последнем Firefox не работает ни xpi, ни userscript (GreaseMonkey 4).

**Comment by nickkolok** [comment]
Наскоро можно решить одним try-catch, в ближайшее время попытаюсь выкатить обновление.

**Comment by nickkolok** [comment]
Так, GreasyMonkey убрали синхронное API  для работы с местным storage. Тут они скорее ССЗБ. С переходом на квантум и так сломалось достаточно много всего, а они ещё и свои API переписали.

Итого планирую сделать chas-correct совместимым с GreaseMonkey 4+ **без поддержки кэширования между страницами**, т.е. работать будет несколько медленнее. Официально совместимость с Firefox Quantum будет через Tampermonkey.

**Comment by drogga** [comment]
Спасибо. Возможно, стоит исправить первую ссылку на https://github.com/nickkolok/chas-correct/blob/master/docs/how-to-install-in-firefox.md (сейчас она указывает на greasemonkey).

**Comment by nickkolok** [comment]
Если есть желание - можете прислать пуллреквест :)
