### ISSUE TITLE
JQuery

### ISSUE THREAD

**Issue by KOLANICH** [nickkolok/chas-correct#7]
JQuery не нужен.

**Comment by nickkolok** [comment]
Патч в студию.

**Comment by nickkolok** [comment]
5cf2ce68215c1726d7eaa675a8ef88ab2b812eb6
0ca5650968483e40e431f08032958e4ad2136ef6
8b53242a493303d5c98df1593a8c9c06f04f454d

**Comment by nickkolok** [comment]
-~50% от размера бинарика. Плюс экономия памяти и времени на инициализацию.
